/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Administrativo;
import controller.AdministrativoController;
import controller.AssistenteController;
import controller.PessoaController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Luciana
 */
public class BuscarAdministrativo extends javax.swing.JFrame {

    /**
     * Creates new form PesquisarFuncionario
     */
    public BuscarAdministrativo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private String flag;
    //private PessoaController pessoaController;
    //private AssistenteController assistenteController;
    private AdministrativoController adminController = new AdministrativoController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        selectNome = new javax.swing.JRadioButton();
        selectMat = new javax.swing.JRadioButton();
        campo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Chaparral Pro", 0, 36)); // NOI18N
        jLabel2.setText("Buscar Administrativo");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(selectNome);
        selectNome.setText("Nome");
        selectNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNomeActionPerformed(evt);
            }
        });

        buttonGroup1.add(selectMat);
        selectMat.setText("Matrícula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(selectNome)
                .addGap(60, 60, 60)
                .addComponent(selectMat)
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectNome)
                    .addComponent(selectMat))
                .addGap(18, 18, 18)
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(buscar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        if(flag.equals("buscar")) {
            this.buscar();
        } else if(flag.equals("editar")) {
            //this.editar();
            //this.setVisible(false);
        } else if(flag.equals("remover")) {
            this.remover();
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void selectNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectNomeActionPerformed
    
    private void buscar() {
        boolean tmp = false;
        Administrativo admin = null;
        List<Administrativo> listAdmin = new ArrayList<Administrativo>();
        
        if(selectNome.isSelected()) {
            if(campo.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Digite um dado no campo para fazer a pesquisa.");
            } else {
                listAdmin = adminController.buscarPorNome(campo.getText());
                tmp = true;
            }
        } else if(selectMat.isSelected()) {
            if(campo.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Digite um dado no campo para fazer a pesquisa.");
            } else {
                admin = adminController.buscarPorMatricula(campo.getText());
                tmp = true;
            }
        } else {
            JOptionPane.showMessageDialog(null,"Nenhum filtro selecionado! Buscando todos os registros...");
            listAdmin = adminController.buscarTodos();
            tmp = true;
        }
        
        if(tmp == true && (admin != null || !listAdmin.isEmpty())) {
            if(admin == null) {
                ExibirFuncionario ef = new ExibirFuncionario();
                ef.preencherTabelaAdmin(listAdmin);
                ef.setVisible(true);
                this.setVisible(false);
            } else if(listAdmin.isEmpty()) {
                ExibirFuncionario ef = new ExibirFuncionario();
                ef.preencherTabelaAdmin(admin);
                ef.setVisible(true);
                this.setVisible(false);
            }
        }
    }
    
    private void remover() {
        Administrativo admin = null;
        List<Administrativo> listAdmin = new ArrayList<Administrativo>();

        if(selectNome.isSelected()) {
            if(campo.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Digite um dado no campo para fazer a exclusão.");
            } else {
                listAdmin = adminController.buscarPorNome(campo.getText());
                JOptionPane.showMessageDialog(null,"Esta ação removerá o seguinte agente administrativo: "+listAdmin.get(0).getPessoa().getNome());
                adminController.removerPorNome(listAdmin.get(0));
                this.dispose();
            }
        } else if(selectMat.isSelected()) {
            if(campo.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Digite um dado no campo para fazer a exclusão.");
            } else {
                admin = adminController.buscarPorMatricula(campo.getText());
                JOptionPane.showMessageDialog(null,"Esta ação removerá o seguinte agente administrativo: "+admin.getPessoa().getNome());
                adminController.removerPorMatricula(admin);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null,"Nenhum filtro selecionado!");
        }
    }
    
    /*private void editar() {
        Administrativo admin = null;
        //List<Administrativo> listAdmin = new ArrayList<Administrativo>();
        GerenciarFuncionario gf = new GerenciarFuncionario();
        gf.setFlag1("editar");
        gf.setFlag2("admin");
        
        if(selectNome.isSelected()) {
            if(campo.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Digite um dado no campo para fazer a alteração.");
            } else {
                admin = adminController.buscarPorNome(campo.getText()).get(0);
                //gf.setFlag2("admin");
                gf.popularCampos(admin);
                gf.setVisible(true);
                this.setVisible(false);
                //adminController.editar(admin);
            }
        } else if(selectMat.isSelected()) {
            if(campo.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Digite um dado no campo para fazer a alteração.");
            } else {
                admin = adminController.buscarPorMatricula(campo.getText());
                //gf.setFlag2("admin");
                gf.popularCampos(admin);
                gf.setVisible(true);
                this.setVisible(false);
                //adminController.editar(admin);
            }
        } else {
            JOptionPane.showMessageDialog(null,"Nenhum filtro selecionado!");
        }
    }*/
    
    public void setFlag(String flag) {
        this.flag = flag;
    }
    
    public void setButton(String acao) {
        this.buscar.setText(acao);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarAdministrativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton selectMat;
    private javax.swing.JRadioButton selectNome;
    // End of variables declaration//GEN-END:variables
    
}
