package view;

import bean.Atendimento;
import controller.AtendimentoController;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class BuscarAtendimento extends javax.swing.JFrame {
    
    /**
     * Creates new form BuscarUsuario
     */
    public BuscarAtendimento() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    //private String flag;
    private AtendimentoController controller = new AtendimentoController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buscar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoAssistente = new javax.swing.JTextField();
        campoData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectNome = new javax.swing.JRadioButton();
        selectAssistente = new javax.swing.JRadioButton();
        selectData = new javax.swing.JRadioButton();
        selectTodos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Chaparral Pro", 0, 36)); // NOI18N
        jLabel2.setText("Buscar Atendimento");

        jLabel1.setText("Nome:");

        jLabel3.setText("Assistente:");

        jLabel4.setText("Data:");

        buttonGroup2.add(selectNome);
        selectNome.setText("Nome");

        buttonGroup2.add(selectAssistente);
        selectAssistente.setText("Assistente");

        buttonGroup2.add(selectData);
        selectData.setText("Data");

        buttonGroup2.add(selectTodos);
        selectTodos.setText("Todos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selectNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selectAssistente)
                                        .addGap(38, 38, 38)
                                        .addComponent(selectData)
                                        .addGap(26, 26, 26)
                                        .addComponent(selectTodos))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoAssistente, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoData)))))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectNome)
                    .addComponent(selectAssistente)
                    .addComponent(selectData)
                    .addComponent(selectTodos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAssistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(buscar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            this.buscar();
        } catch (ParseException ex) {
            Logger.getLogger(BuscarAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void buscar() throws ParseException {
        ArrayList array = new ArrayList();

	if(selectNome.isSelected() && campoNome != null) {
            array = controller.buscarPorUsuario(campoNome.getText());
        } else if(selectData.isSelected() && campoData != null) {
            array = controller.buscarPorData(campoData.getText());
        } else if(selectAssistente.isSelected() && campoAssistente != null) {
            array = controller.buscarPorAssistente(campoAssistente.getText());
        } else if(selectTodos.isSelected()) {
            array = controller.buscarTodos();
        } else {
            JOptionPane.showMessageDialog(null,"Nenhuma opção definida. Tente novamente.");
        }

        if(!array.isEmpty()) {
            ExibirAtendimento ea = new ExibirAtendimento();
            ea.preencherTabela(array);
            ea.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null,"Sua busca não retornou nenhum resultado.\nTalvez seja melhor usar outro filtro?");
        }
    }
    
    /*private void editar() {
        Atendimento atendimento;
        if(selectNome.isSelected() && campoNome != null) {
            atendimento = controller.buscarPorUsuario(campoNome.getText());
        } else if(selectData.isSelected() && campoData != null) {
            atendimento = controller.buscarPorData(campoData.getText());
        } else if(selectAssistente.isSelected() && campoAssistente != null) {
            atendimento = controller.buscarPorAssistente(campoAssistente.getText());
        } else {
            atendimento = controller.buscarTodos();
        }

        GerenciarAtendimento ga = new GerenciarAtendimento();
        ga.setFlag(this.flag);
        ga.setVisible(true);
        this.setVisible(false);
    }*/

    /*private void remover() {

        if(selectNome.isSelected() && campoNome != null) {
            controller.removerPorString(campoNome.getText());
        } else if(selectData.isSelected() && campoData != null) {
            controller.removerPorString(campoData.getText());
        } else if(selectAssistente.isSelected() && campoAssistente != null) {
            controller.removerPorString(campoAssistente.getText());
        } else {
            JOptionPane.showMessageDialog(null,"Nenhuma opção definida. Tente novamente.");
    }

        /*if(tmp) {

            JOptionPane.showMessageDialog(null,"Nenhuma opção definida. Tente novamente.");

        }

    }*/

    /*public void setFlag(String flag) {
        this.flag = flag;
    }*/

    public void setButton(String acao) {
        this.buscar.setText(acao);
    }

    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 
        */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(BuscarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(BuscarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(BuscarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(BuscarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>


        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new BuscarAtendimento().setVisible(true);

            }

        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoAssistente;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton selectAssistente;
    private javax.swing.JRadioButton selectData;
    private javax.swing.JRadioButton selectNome;
    private javax.swing.JRadioButton selectTodos;
    // End of variables declaration//GEN-END:variables

}
