/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luciana
 */
public class ExibirUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ExibirUsuario
     */
    public ExibirUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prontuário", "1º Atendimento", "Status", "Nome", "Data de Nascimento"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel3.setFont(new java.awt.Font("Chaparral Pro", 0, 36)); // NOI18N
        jLabel3.setText("Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void preencherTabela(ArrayList<Usuario> user) {
        for(int i=0; i<user.size(); i++){
            DefaultTableModel modeloTabela = (DefaultTableModel)jTable1.getModel(); 
            modeloTabela.addRow(new String[ modeloTabela.getColumnCount() ]);      
            jTable1.setValueAt(user.get(i).getProntuario(),i, 0);
            jTable1.setValueAt(user.get(i).getPrimeiroAtendimento(),i, 1);
            jTable1.setValueAt(user.get(i).getStatus(),i, 2);
            jTable1.setValueAt(user.get(i).getPessoa().getNome(),i, 3);
            jTable1.setValueAt(user.get(i).getPessoa().getNascimento(),i, 4);
            //jTable1.setValueAt("",i, 5);
            //jTable1.setValueAt(user.get(i).getDocumentos(),i, 6);
            //jTable1.setValueAt(user.get(i).getDocumentos(),i, 7);
            //jTable1.setValueAt(user.get(i).getDocumentos(),i, 8);
        }
    }
    
    public void preencherTabela(Usuario user) {

        DefaultTableModel modeloTabela = (DefaultTableModel)jTable1.getModel(); 
        modeloTabela.addRow(new String[ modeloTabela.getColumnCount() ]);      
        jTable1.setValueAt(user.getProntuario(),0, 0);
        jTable1.setValueAt(user.getPrimeiroAtendimento(),0, 1);
        jTable1.setValueAt(user.getStatus(),0, 2);
        jTable1.setValueAt(user.getPessoa().getNome(),0, 3);
        jTable1.setValueAt(user.getPessoa().getNascimento(),0, 4);
        //jTable1.setValueAt("",i, 5);
        //jTable1.setValueAt(user.get(i).getDocumentos(),i, 6);
        //jTable1.setValueAt(user.get(i).getDocumentos(),i, 7);
        //jTable1.setValueAt(user.get(i).getDocumentos(),i, 8);
    }
    
    /*public void setFiltro(String filtro) {
        this.jLabel4.setText("Filtro: "+filtro);
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
