package view;

import bean.Administrativo;
import bean.AssistenteSocial;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ExibirFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form ExibirUsuario
     */
    public ExibirFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Chaparral Pro", 0, 36)); // NOI18N
        jLabel2.setText("Buscar Atendimento");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome", "Data de Nascimento", "Cargo", "Função"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel3.setFont(new java.awt.Font("Chaparral Pro", 0, 36)); // NOI18N
        jLabel3.setText("Funcionários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void preencherTabelaAdmin(Administrativo admin) {
        DefaultTableModel modeloTabela = (DefaultTableModel)jTable1.getModel(); 
        modeloTabela.addRow(new String[ modeloTabela.getColumnCount() ]);      
        jTable1.setValueAt(admin.getMatricula(), 0, 0);
        jTable1.setValueAt(admin.getPessoa().getNome(), 0, 1);
        jTable1.setValueAt(admin.getPessoa().getNascimento(), 0, 2);
        jTable1.setValueAt("Administrativo", 0, 3);
        jTable1.setValueAt(admin.getFuncao(), 0, 4);
        //jTable1.setValueAt(admin.getPessoa().getTelefones(), 0, 5);
    }
    
    public void preencherTabelaAdmin(List<Administrativo> admin) {
        for(int i=0; i<admin.size(); i++) {
            DefaultTableModel modeloTabela = (DefaultTableModel)jTable1.getModel(); 
            modeloTabela.addRow(new String[ modeloTabela.getColumnCount() ]);      
            jTable1.setValueAt(admin.get(i).getMatricula(), i, 0);
            jTable1.setValueAt(admin.get(i).getPessoa().getNome(), i, 1);
            jTable1.setValueAt(admin.get(i).getPessoa().getNascimento(), i, 2);
            jTable1.setValueAt("Administrativo", i, 3);
            jTable1.setValueAt(admin.get(i).getFuncao(), i, 4);
            //jTable1.setValueAt(admin.getPessoa().getTelefones(), 0, 5);
        }
    }
    
    public void preencherTabelaAssist(AssistenteSocial assist) {
        DefaultTableModel modeloTabela = (DefaultTableModel)jTable1.getModel(); 
        modeloTabela.addRow(new String[ modeloTabela.getColumnCount() ]);      
        jTable1.setValueAt(assist.getMatricula(), 0, 0);
        jTable1.setValueAt(assist.getPessoa().getNome(), 0, 1);
        jTable1.setValueAt(assist.getPessoa().getNascimento(), 0, 2);
        jTable1.setValueAt("Assistente Social", 0, 3);
        jTable1.setValueAt("Atendimento", 0, 4);
        //jTable1.setValueAt(as.getPessoa().getTelefones(), 0, 5);
    }
    
    public void preencherTabelaAssist(List<AssistenteSocial> assist) {
        for(int i=0; i<assist.size(); i++) {
            DefaultTableModel modeloTabela = (DefaultTableModel)jTable1.getModel(); 
            modeloTabela.addRow(new String[ modeloTabela.getColumnCount() ]);      
            jTable1.setValueAt(assist.get(i).getMatricula(), i, 0);
            jTable1.setValueAt(assist.get(i).getPessoa().getNome(), i, 1);
            jTable1.setValueAt(assist.get(i).getPessoa().getNascimento(), i, 2);
            jTable1.setValueAt("Administrativo", i, 3);
            jTable1.setValueAt("Atendimento", i, 4);
            //jTable1.setValueAt(admin.getPessoa().getTelefones(), 0, 5);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
