/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Administrativo;
import bean.AssistenteSocial;
import bean.Pessoa;
import controller.AdministrativoController;
import controller.AssistenteController;
import controller.FormatarData;
import controller.PessoaController;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author a1600061
 */
public class GerenciarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarFuncionarioJ
     */
    public GerenciarFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private String flag1; //edição ou adição
    private String flag2; //admin ou assist
    
    private AdministrativoController adminController = new AdministrativoController();
    private AssistenteController assistController = new AssistenteController();
    private PessoaController pessoaController = new PessoaController();
    private Pessoa pessoa = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoMat = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        campoFuncao = new javax.swing.JTextField();
        campoNasc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Chaparral Pro", 0, 36)); // NOI18N
        jLabel2.setText("Gerenciar Funcionário");

        jLabel3.setText("Nome:");

        jLabel4.setText("Data de Nascimento:");

        jLabel5.setText("Matrícula:");

        campoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMatActionPerformed(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jLabel7.setText("Função:");

        campoFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFuncaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoMat)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoFuncao)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(salvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMatActionPerformed
    
    /*
     * Botão salvar
     */
    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        if(flag2.equalsIgnoreCase("admin")) {
            this.salvarAdmin();
        } else if(flag2.equalsIgnoreCase("assist")) { 
            this.salvarAssist();
        } else {
            JOptionPane.showMessageDialog(null,"Erro! 404 NOT FOUND");
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void campoFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFuncaoActionPerformed
        
    }//GEN-LAST:event_campoFuncaoActionPerformed
    
    /*
     * Edição
     */
    
    public void popularCampos(Administrativo admin) {
        this.campoMat.setText(admin.getMatricula());
        this.campoNasc.setText(admin.getPessoa().getNascimento().toString());
        this.campoNome.setText(admin.getPessoa().getNome());
        this.campoFuncao.setText(admin.getFuncao());
        pessoa = pessoaController.buscarPorNomeUnico(campoNome.getText());
    }
    
    public void popularCampos(AssistenteSocial assist) {
        this.campoMat.setText(assist.getMatricula());
        this.campoNasc.setText(assist.getPessoa().getNascimento().toString());
        this.campoNome.setText(assist.getPessoa().getNome());
        pessoa = pessoaController.buscarPorNomeUnico(campoNome.getText());
    }
    
    /*
     * MÉTODOS DE SALVAR
     */
    private void salvarAdmin() {
        if(!campoMat.getText().equals("") && !campoNasc.getText().equals("") &&
                !campoNome.getText().equals("") && !campoFuncao.getText().equals("")) {
            String matricula = campoMat.getText();
            String nasc = campoNasc.getText();
            String nome = campoNome.getText();
            String funcao = campoFuncao.getText();
            
            Date novaData = new Date();
            
            try {
                FormatarData fd = new FormatarData(nasc);
                novaData = fd.getData();
            } catch (ParseException ex) {
                Logger.getLogger(GerenciarAtendimento.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            if(flag1.equalsIgnoreCase("editar")) {
                Administrativo admin = adminController.buscarPorIdPessoa(pessoa.getIdPessoa());
                pessoaController.editar(pessoa);
                pessoaController.ac.editar(admin);
            } else if(flag1.equalsIgnoreCase("add")) {
                PessoaController pc = new PessoaController(nome, novaData, funcao, matricula);
                pc.salvar();
                pc.ac.salvar();
            }
            
            JOptionPane.showMessageDialog(null,"Administrativo cadastrado com sucesso!");
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos.");
        }
    }
    
    private void salvarAssist() {
        if(!campoMat.getText().equals("") && !campoNasc.getText().equals("") && !campoNome.getText().equals("")) {
            String matricula = campoMat.getText();
            String nasc = campoNasc.getText();
            String nome = campoNome.getText();
            
            Date novaData = new Date();
            
            //AssistenteSocial asc = assistController.buscarPorMatricula(campoMat.getText());
            
            try {
                FormatarData fd = new FormatarData(nasc);
                novaData = fd.getData();
            } catch (ParseException ex) {
                Logger.getLogger(GerenciarAtendimento.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            if(flag1.equalsIgnoreCase("editar")) {
                AssistenteSocial assist = assistController.buscarPorIdPessoa(pessoa.getIdPessoa());
                pessoaController.editar(pessoa);
                pessoaController.asc.editar(assist);
            } else if(flag1.equalsIgnoreCase("add")) {
                PessoaController pc = new PessoaController(nome, novaData, matricula);
                pc.salvar();
                pc.asc.salvar();
            }
            
            JOptionPane.showMessageDialog(null,"Assistente Social cadastrado com sucesso!");
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos.");
        }
    }
    
    /*
     * Set de flags para auxílio
     */
    
    public void setFlag1(String flag) {
        this.flag1 = flag;
    }
    
    public void setFlag2(String flag) {
        this.flag2 = flag;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoFuncao;
    private javax.swing.JTextField campoMat;
    private javax.swing.JTextField campoNasc;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
